/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/i2QtReNQ0Z4
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import ThreeScene from "./model";
import Model from "./model";
export function Component() {
  return (
    <div className="flex flex-col w-full ">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link
          href="#"
          className="flex items-center justify-center"
          prefetch={false}
        >
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Crypto Launchpad</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Exchange
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Create ICO
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Create Token
          </Link>
          <Link
            href="#"
            className="text-sm font-medium hover:underline underline-offset-4"
            prefetch={false}
          >
            Transfer Token
          </Link>
        </nav>
      </header>
      <main className="flex flex-col flex-1 w-full items-center">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48 flex justify-center">
          <div className="container px-4 md:px-6 w-full">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
                    Revolutionize Your University Credits
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                  Unlock decentralized credit transfers with our crypto ICO platform, streamlining credit exchange for university students.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Explore Exchange
                  </Link>
                </div>
              </div>
              {/* <img
                src="/coins.webp"
                width="550"
                height="550"
                alt="Hero"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
              /> */}
              <ThreeScene/>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 flex justify-center">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Explore the Credit Exchange
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                

Browse our selection of university credit tokens and ICOs, and invest in the future of blockchain-based credit transfers.

                </p>
              </div>
              <div className="w-full max-w-4xl">
                <div className="rounded-lg border">
                  <div className="grid grid-cols-[repeat(6,minmax(0,1fr))] items-center border-b p-4 font-medium">
                    <div>Name</div>
                    <div>Symbol</div>
                    <div>Total Supply</div>
                    <div>Token</div>
                    <div>University</div>
                    <div></div>
                  </div>
                  <div className="divide-y">
                    <div className="grid grid-cols-[repeat(6,minmax(0,1fr))] items-center p-4">
                      <div>IIT Madras Credits</div>
                      <div>IITM</div>
                      <div>21,000</div>
                      <div>0x1234...567</div>
                      <div>Indian Institue of Technology Madras</div>
                      <div className="">
                        <Button>Exchange</Button>
                      </div>
                    </div>
                    <div className="grid grid-cols-[repeat(6,minmax(0,1fr))] items-center p-4">
                      <div>IIT Bombay Credits</div>
                      <div>IITB</div>
                      <div>120,000</div>
                      <div>0x1234...567</div>
                      <div>Indian Institute of Technology Bombay</div>
                      <div>
                        <Button>Exchange</Button>
                      </div>
                    </div>
                    <div className="grid grid-cols-[repeat(6,minmax(0,1fr))] items-center p-4">
                      <div>IIT Delhi Credits</div>
                      <div>IITD</div>
                      <div>500,000</div>
                      <div>0x1234...567</div>
                      <div>Indian Institute of Technology Madras</div>
                      <div>
                        <Button>Exchange</Button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex gap-4">
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  Create ICO
                </Link>
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md border border-input bg-background px-8 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  Create Token
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted flex justify-center">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-10">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Create Your Own ICO
                </h2>
                <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Launch your credit token as an ICO, enabling students to exchange their credits.
                </p>
              </div>
              <div className="rounded-lg border p-6 w-full">
              <h3 className="text-xl font-bold">Create ICO</h3>
                <form className="space-y-4">
                  <div>
                    <Label htmlFor="token-name">Token Name</Label>
                    <Input
                      id="token-name"
                      type="text"
                      placeholder="Enter token name"
                      className="w-full"
                    />
                  </div>
                  <div>
                    <Label htmlFor="token-symbol">Token Symbol</Label>
                    <Input
                      id="token-symbol"
                      type="text"
                      placeholder="Enter token symbol"
                      className="w-full"
                    />
                  </div>
                  <div>
                    <Label htmlFor="total-supply">Total Supply</Label>
                    <Input
                      id="total-supply"
                      type="number"
                      placeholder="Enter total supply"
                      className="w-full"
                    />
                  </div>
                  <div className="space-y-2">
                    <h4 className="text-lg font-bold">ICO Details Preview</h4>
                    <div className="grid grid-cols-[minmax(0,1fr)_minmax(0,1fr)] gap-2">
                      <span>Token Name:</span>
                      <span>Example Token</span>
                      <span>Token Symbol:</span>
                      <span>EXT</span>
                      <span>Total Supply:</span>
                      <span>1,000,000</span>
                    </div>
                  </div>
                  <Button type="submit" className="w-full">
                    Create ICO
                  </Button>
                </form>
              </div>
            </div>
          </div>
        </section>

        <section className="w-full py-12 md:py-24 lg:py-32 flex justify-center">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                Mint Your Credit Token
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Create your own custom crypto credit token for your students and list it on our exchange.
                </p>
              </div>
              <div className="rounded-lg border p-6 w-full max-w-2xl">
                <h3 className="text-xl font-bold">Create Token</h3>
                <form className="space-y-4">
                  <div>
                    <Label htmlFor="token-name">Token Name</Label>
                    <Input
                      id="token-name"
                      type="text"
                      placeholder="Enter token name"
                      className="w-full"
                    />
                  </div>
                  <div>
                    <Label htmlFor="token-symbol">Token Symbol</Label>
                    <Input
                      id="token-symbol"
                      type="text"
                      placeholder="Enter token symbol"
                      className="w-full"
                    />
                  </div>
                  <div>
                    <Label htmlFor="total-supply">Total Supply</Label>
                    <Input
                      id="total-supply"
                      type="number"
                      placeholder="Enter total supply"
                      className="w-full"
                    />
                  </div>
                  <div>
                    <Label htmlFor="decimals">Decimals</Label>
                    <Input
                      id="decimals"
                      type="number"
                      placeholder="Enter number of decimals"
                      className="w-full"
                    />
                  </div>
                  <div className="space-y-2">
                    <h4 className="text-lg font-bold">Token Details Preview</h4>
                    <div className="grid grid-cols-[minmax(0,1fr)_minmax(0,1fr)] gap-2">
                      <span>Token Name:</span>
                      <span>Example Token</span>
                      <span>Token Symbol:</span>
                      <span>EXT</span>
                      <span>Total Supply:</span>
                      <span>1,000,000</span>
                      <span>Decimals:</span>
                      <span>18</span>
                    </div>
                  </div>
                  <Button type="submit" className="w-full">Create Credit</Button>
                </form>
              </div>
            </div>
          </div>
        </section>

        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted flex justify-center">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-2 lg:gap-10">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
                Easy Credit Transfers
                </h2>
                <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Transfer credits with one click—only you, the university, can do it. Students can exchange them for credits at other universities.
                </p>
              </div>
              <div className="rounded-lg border p-6 w-full">
              <h3 className="text-xl font-bold">Create ICO</h3>
                <form className="space-y-4">
                <div>
                    <Label htmlFor="student-address">Student Address</Label>
                    <Input
                      id="student-address"
                      type="text"
                      placeholder="Enter token address"
                      className="w-full"
                    />
                  </div>
                  <div>
                    <Label htmlFor="token-address">Token Address</Label>
                    <Input
                      id="token-address"
                      type="text"
                      placeholder="Enter token address"
                      className="w-full"
                    />
                  </div>
                  <div>
                    <Label htmlFor="amount">Amount</Label>
                    <Input
                      id="total-supply"
                      type="number"
                      placeholder="Enter amount"
                      className="w-full"
                    />
                  </div>
                  <Button type="submit" className="w-full">
                    Transfer Credits
                  </Button>
                </form>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

function MountainIcon(props: any) {
  return (
    // <svg
    //   {...props}
    //   xmlns="http://www.w3.org/2000/svg"
    //   width="24"
    //   height="24"
    //   viewBox="0 0 24 24"
    //   fill="none"
    //   stroke="currentColor"
    //   strokeWidth="2"
    //   strokeLinecap="round"
    //   strokeLinejoin="round"
    //   s
    // >
    // </svg>
    <img {...props} src="/logo1.svg" className="text-black" width={48} height={48}/>
  );
}
